apiVersion: v1
kind: Service
metadata:
  name: ms-peliculas-favoritos-backend
  labels:
    app: ms-peliculas-favoritos-backend
spec:
  type: NodePort
  selector:
    app: ms-peliculas-favoritos-backend
  ports:
  - protocol: TCP
    port: 9081
    targetPort: 9081
    nodePort: 30081